version: '3'

services:
  rabbitmq:
    build: docker/rabbitmq
    image: rabbitmq:${RABBITMQ_IMAGE_VERSION}
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${MESSENGER_TRANSPORT_USER}
      RABBITMQ_DEFAULT_PASS: ${MESSENGER_TRANSPORT_SECRET}
      RABBITMQ_PID_FILE: /var/lib/rabbitmq/rabbitmq.pid
    ports:
      - "5673:5672"
      - "15673:15672"
